#pragma once

#include "driver/gpio.h"
#include "hal/adc_types.h"

#define APP_DEVICE_ID_PREFIX "GRAESP"

// ESP32-S3-WROOM-1-N16R8 pin plan for the first PCB revision.
// ADC1 is preferred because it stays usable when Wi-Fi is enabled.
#define APP_NTC1_ADC_CHANNEL ADC_CHANNEL_3      // GPIO4, cable NTC 1
#define APP_NTC2_ADC_CHANNEL ADC_CHANNEL_4      // GPIO5, cable NTC 2
#define APP_NTC_ENV_ADC_CHANNEL ADC_CHANNEL_5   // GPIO6, ambient NTC
#define APP_BAT_ADC_CHANNEL ADC_CHANNEL_6       // GPIO7, battery divider

#define APP_NTC_POWER_GPIO GPIO_NUM_15          // optional switched NTC divider supply
#define APP_LED_GPIO GPIO_NUM_18                // status LED
#define APP_BUZZER_GPIO GPIO_NUM_17             // buzzer drive or PWM pin

#define APP_USB_D_MINUS_GPIO GPIO_NUM_19
#define APP_USB_D_PLUS_GPIO GPIO_NUM_20
#define APP_BOOT_GPIO GPIO_NUM_0
#define APP_UART0_TX_GPIO GPIO_NUM_43
#define APP_UART0_RX_GPIO GPIO_NUM_44

#define APP_WIFI_SSID "TT24"
#define APP_WIFI_PASSWORD "88888888"
#define APP_WIFI_CONNECT_TIMEOUT_MS 10000
#define APP_PROV_AP_PREFIX "GraEsp"
#define APP_PROV_AP_PASSWORD "12345678"
#define APP_WIFI_NVS_NAMESPACE "wifi"
#define APP_TELEMETRY_UDP_PORT 3333
#define APP_COMMAND_UDP_PORT 3334
#define APP_TELEMETRY_UDP_BROADCAST "255.255.255.255"
#define APP_WIFI_RECOVERY_CHECK_MS 15000
#define APP_WIFI_MODEM_SLEEP_ENABLE 1
#define APP_WIFI_SCAN_MAX_AP 12
#define APP_MQTT_ENABLE 1
#define APP_MQTT_BROKER_HOST "broker.emqx.io"
#define APP_MQTT_BROKER_PORT 1883
#define APP_MQTT_BASE_TOPIC "graesp/lin"
#define APP_MQTT_KEEPALIVE_S 60
#define APP_MQTT_RECONNECT_MS 10000

#define APP_BOARD_TEST_LED_ALWAYS_ON 0
#define APP_BOARD_TEST_LED_BUZZER_ALTERNATE 0
#define APP_BOARD_TEST_ALTERNATE_PERIOD_MS 500

#define APP_BUZZER_ACTIVE_LEVEL 0
#define APP_BUZZER_INACTIVE_LEVEL 1

#define APP_SAMPLE_PERIOD_MS 1000
#define APP_LOW_BATTERY_SAMPLE_PERIOD_MS 3000
#define APP_CRITICAL_BATTERY_SAMPLE_PERIOD_MS 10000
#define APP_TELEMETRY_UPLOAD_PERIOD_MS 1000
#define APP_LOW_BATTERY_UPLOAD_PERIOD_MS 5000
#define APP_CRITICAL_BATTERY_UPLOAD_PERIOD_MS 15000
#define APP_NTC_POWER_SETTLE_US 2000
#define APP_ADC_ATTEN ADC_ATTEN_DB_12
#define APP_ADC_VREF_MV 3300.0f

// Divider assumption: 3V3 -> fixed resistor -> ADC node -> NTC -> GND.
#define APP_NTC_R_FIXED_OHM 10000.0f
#define APP_NTC_R0_OHM 10000.0f
#define APP_NTC_BETA 3950.0f
#define APP_NTC_T0_K 298.15f

// Battery divider assumption: BAT+ -> R_TOP -> ADC node -> R_BOTTOM -> GND.
#define APP_BAT_R_TOP_OHM 200000.0f
#define APP_BAT_R_BOTTOM_OHM 100000.0f

#define APP_NTC_ADC_MIN_MV 50
#define APP_NTC_ADC_MAX_MV 3250
#define APP_NTC_MIN_TEMP_C (-20.0f)
#define APP_NTC_MAX_TEMP_C 110.0f

#define APP_BATTERY_MIN_VALID_V 2.0f
#define APP_BATTERY_MAX_VALID_V 4.6f
#define APP_BATTERY_EMPTY_V 3.30f
#define APP_BATTERY_FULL_V 4.20f
#define APP_BATTERY_LOW_V 3.55f
#define APP_BATTERY_CRITICAL_V 3.30f

#define APP_FILTER_ALPHA 0.25f

#define APP_USE_EDGE_AI_MODEL 1
#define APP_MODEL_WARNING_PROBABILITY 0.60f
#define APP_MODEL_OVERLOAD_PROBABILITY 0.85f
#define APP_MODEL_WARNING_MIN_TEMP_RISE_C 8.5f
#define APP_MODEL_OVERLOAD_MIN_TEMP_RISE_C 10.0f
#define APP_MODEL_LOW_RISE_PROBABILITY_CAP 0.45f
#define APP_MODEL_PRE_OVERLOAD_PROBABILITY_CAP 0.78f

// Calibrated for the current 10 A plug-strip experiment target.
#define APP_WARNING_CURRENT_A 9.0f
#define APP_OVERLOAD_CURRENT_A 10.0f
#define APP_TEMP_HIGH_TEMP_RISE_C 6.5f
#define APP_WARNING_TEMP_RISE_C 8.5f
#define APP_OVERLOAD_TEMP_RISE_C 12.0f

#define APP_TEMP_HIGH_CONFIRM_MS 3000
#define APP_WARNING_CONFIRM_MS 5000
#define APP_OVERLOAD_CONFIRM_MS 8000
#define APP_STATE_RECOVERY_MS 10000
#define APP_TEMP_HIGH_RELEASE_TEMP_RISE_C 5.0f
#define APP_WARNING_RELEASE_TEMP_RISE_C 6.5f
#define APP_OVERLOAD_RELEASE_TEMP_RISE_C 9.0f
#define APP_TEMP_HIGH_RELEASE_RATE_C_PER_MIN 1.5f
#define APP_WARNING_RELEASE_RATE_C_PER_MIN 3.0f
#define APP_OVERLOAD_RELEASE_RATE_C_PER_MIN 4.0f




