idf_component_register(
    SRCS
        "app_main.c"
        "src/gateway_telemetry.c"
        "src/tjc_screen.c"
        "src/udp_receiver.c"
        "src/wifi_station.c"
    INCLUDE_DIRS
        "include"
    REQUIRES
        esp_driver_gpio
        esp_driver_uart
        esp_event
        esp_netif
        esp_wifi
        lwip
        nvs_flash
)
